### ISSUE TITLE
A small question to Pavani

### ISSUE THREAD

**Issue by testingweb624** [PAVANINADELLA/DATA-SCIENCE-NOTES#1]
Hi, Pavani.

I am very interested in data science. Is following this Notes is sufficient for getting an internship or entry level job in companies. Can you please clarify this. I will be looking forward to your response.

**Comment by testingweb624** [comment]
Hi, Pavani. Thanks for replying back. I already started learning from your resources. 

Hope I could placed in any good startup /MNC. BTW can I seek your reference for joining/interview :)  in coming days.

**Comment by PAVANINADELLA** [comment]
Yes, for sure. You can follow all of our resources.

Wish you All the best and get placed in a good MNC with a good designation. Take care.
