### ISSUE TITLE
Rename files to sort by SerialNumber

### ISSUE THREAD

**Issue by peeush-the-developer** [PAVANINADELLA/DATA-SCIENCE-NOTES#2]
I think if we rename PDF files, then they can appear in a sorted manner by Serial Number.

**Comment by PAVANINADELLA** [comment]
Hello.
Good Morning.
Hope you're doing good and safe.
Well, I have uploaded all the documents in a Sequence manner. Don't know why they are a bit jumbled.
Any way I'll try again and check okay.

Thank you & Best Regards.,
PAVANI NADELLA.

**Comment by peeush-the-developer** [comment]
Hey @PAVANINADELLA,
Hope you're doing well and be safe.
I've actually fixed it in the PR #3. 
May be you can have a look and merge it if that's acceptable.

Thanks

**Comment by PAVANINADELLA** [comment]
Okay.
